### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by jlesquembre**

### CODE REVIEW

**Comment by JonathanLorimer** [comment]
@jlesquembre Wow, thank you so much for taking care of this!

**Comment by JonathanLorimer** [comment]
@jlesquembre unfortunately I get this error when running the app after building:
```
maelstrom.nix on  main [!]
λ ./result/bin/maelstrom
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.core.matrix.impl.mathsops, being replaced by: #'clojure.core.matrix.impl.mathsops/abs
Warning: protocol #'clojure.core.matrix.protocols/PMathsFunctions is overwriting function abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.core.matrix.protocols, being replaced by: #'clojure.core.matrix.protocols/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.core.matrix, being replaced by: #'clojure.core.matrix/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.core.matrix.dataset, being replaced by: #'clojure.core.matrix/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: incanter.core, being replaced by: #'incanter.core/abs
Usage: lein run -- COMMAND [OPTIONS ...]
Commands: analyze, demo, doc, serve, test
```

Perhaps there are some runtime inputs that need to be included?

**Comment by jlesquembre** [comment]
The `lein` part is confusing, try:
`./result/bin/maelstrom test --help`

**Comment by JonathanLorimer** [comment]
Oh yeah, you are right, I just needed to call it with the correct argument! Thanks!

**Pull request merged**
